In [1]:
import numpy as np

In [ ]:
np?

In [3]:
np.array([range(i,i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5), 52)

array([[52, 52, 52, 52, 52],
       [52, 52, 52, 52, 52],
       [52, 52, 52, 52, 52]])

In [12]:
np.random.random((3,3))

array([[0.36070919, 0.3087754 , 0.67327567],
       [0.40519561, 0.63114156, 0.0165086 ],
       [0.06125143, 0.18754944, 0.61002156]])

In [13]:
np.random.normal(0,1, (3,3))

array([[ 0.16093056,  1.93455584, -0.12988314],
       [-0.47786159, -0.75252238,  1.78814866],
       [ 0.25708286,  2.00901407,  1.61870282]])

In [15]:
np.empty(3)

array([2.96439388e-323, 0.00000000e+000, 2.12199579e-314])

In [16]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [17]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
