In [1]:
import numpy as np

In [ ]:
np?

In [2]:
np.array([range(i,i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3,5), 52)

array([[52, 52, 52, 52, 52],
       [52, 52, 52, 52, 52],
       [52, 52, 52, 52, 52]])

In [6]:
np.random.random((3,3))

array([[0.09110615, 0.09870587, 0.01626199],
       [0.31662497, 0.88585142, 0.72227354],
       [0.81268989, 0.23668837, 0.09247465]])

In [7]:
np.random.normal(0,1, (3,3))

array([[-1.82919462,  0.1805908 , -0.38845841],
       [-2.09770169, -1.45626973, -0.22497769],
       [-1.26222122,  0.13897476, -2.78506754]])

In [8]:
np.empty(3)

array([0., 0., 0.])

In [9]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[2,0]

1

In [17]:
x2[0,3]

4

In [18]:
x2[2,2]

7